apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: server-container
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: {{ .Values.server.healthCheck.liveness.path }}
              port: {{ .Values.server.service.targetPort }}
            initialDelaySeconds: {{ .Values.server.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.healthCheck.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.server.healthCheck.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.server.healthCheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.healthCheck.readiness.path }}
              port: {{ .Values.server.service.targetPort }}
            initialDelaySeconds: {{ .Values.server.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.healthCheck.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.server.healthCheck.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.server.healthCheck.readiness.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
