apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: web-container
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.healthCheck.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.healthCheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.healthCheck.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.healthCheck.readiness.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}